name: Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yusufhm/udp-listener

jobs:

  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@master

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@master
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@master
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@master
      with:
        context: .
        provenance: false
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
